In [1]:
import zipfile
import pandas as pd
from pathlib import Path
import ast
import numpy as np

In [ ]:
zip_path = Path("filtered_subs_and_threads_anonymized.zip")
out_dir = Path("data")

with zipfile.ZipFile(zip_path) as z:
    z.extractall(out_dir)
    
root = Path("data/filtered_subs_and_threads_anonymized")

In [14]:
for sub in ["submissions", "threads"]:
    for d in sorted((root / sub).iterdir()):
        n = len(list(d.rglob("*.*")))
        print(sub, d.name, n, "files")
        
f = next((root/"threads").rglob("*_scored.csv"))
print(f)
pd.read_csv(f).head()

submissions subreddit0_2020-07-01_2022-12-31 1 files
submissions subreddit1_2020-07-01_2022-12-31 1 files
submissions subreddit2_2020-07-01_2022-12-31 1 files
submissions subreddit3_2020-07-01_2022-12-31 1 files
submissions subreddit4_2020-07-01_2022-12-31 1 files
submissions subreddit5_2020-07-01_2022-12-31 1 files
threads subreddit0_2020-07-01_2022-12-31 181 files
threads subreddit1_2020-07-01_2022-12-31 148 files
threads subreddit2_2020-07-01_2022-12-31 2429 files
threads subreddit3_2020-07-01_2022-12-31 385 files
threads subreddit4_2020-07-01_2022-12-31 490 files
threads subreddit5_2020-07-01_2022-12-31 2618 files
data/filtered_subs_and_threads_anonymized/threads/subreddit4_2020-07-01_2022-12-31/lowvyz_scored.csv

,comm_id,sub_id,parent_id,subreddit_id,author_id,created_at,predicted_stance_scores
0,comm71631,t3_sub3423,t1_comm71632,r/4,author26899,2021-02-22 04:26:38,NI
1,comm71633,t3_sub3423,t1_comm71634,r/4,author26899,2021-02-22 04:25:20,0.0
2,comm71635,t3_sub3423,t1_comm71636,r/4,author19952,2021-02-21 20:33:18,NI
3,comm71634,t3_sub3423,t1_comm71637,r/4,author26900,2021-02-21 18:09:22,0.5
4,comm71636,t3_sub3423,t3_sub3423,r/4,author1577,2021-02-21 16:49:42,0.0

In [15]:
def load_folder(base):
    dfs = []
    for f in Path(base).rglob("*.csv"):
        d = pd.read_csv(f)
        d["subreddit"] = f.parent.name.split("_")[0]   # e.g. subreddit2
        d["thread_id"] = f.stem.replace("_scored", "")  # e.g. hk0mv9
        dfs.append(d)
    return pd.concat(dfs, ignore_index=True)

threads = load_folder(root / "threads")
submissions = load_folder(root / "submissions")

print(threads.shape, submissions.shape)

(282497, 9) (6251, 7)

In [16]:
threads.thread_id.nunique()

6251

In [5]:
threads.head(10)

,comm_id,sub_id,parent_id,subreddit_id,author_id,created_at,predicted_stance_scores,subreddit,thread_id
0,comm71631,t3_sub3423,t1_comm71632,r/4,author26899,2021-02-22 04:26:38,NI,subreddit4,lowvyz
1,comm71633,t3_sub3423,t1_comm71634,r/4,author26899,2021-02-22 04:25:20,0.0,subreddit4,lowvyz
2,comm71635,t3_sub3423,t1_comm71636,r/4,author19952,2021-02-21 20:33:18,NI,subreddit4,lowvyz
3,comm71634,t3_sub3423,t1_comm71637,r/4,author26900,2021-02-21 18:09:22,0.5,subreddit4,lowvyz
4,comm71636,t3_sub3423,t3_sub3423,r/4,author1577,2021-02-21 16:49:42,0.0,subreddit4,lowvyz
5,comm71638,t3_sub3423,t3_sub3423,r/4,author458,2021-02-21 16:30:23,0.0,subreddit4,lowvyz
6,comm71639,t3_sub3423,t3_sub3423,r/4,author26217,2021-02-21 16:25:18,0.0,subreddit4,lowvyz
7,comm71640,t3_sub3423,t3_sub3423,r/4,author20722,2021-02-21 16:17:39,0.0,subreddit4,lowvyz
8,comm71637,t3_sub3423,t1_comm71641,r/4,author26217,2021-02-21 16:15:13,0.0,subreddit4,lowvyz
9,comm71642,t3_sub3423,t1_comm71643,r/4,author20727,2021-02-21 15:06:49,0.5,subreddit4,lowvyz

In [23]:
submissions.head(10)

,subreddit_id,sub_id,author_id,created_at,predicted_stance_scores,subreddit,thread_id
0,r/4,sub3143,author1756,2022-11-12 17:34:37,0.95,subreddit4,subreddit4_subs_anon
1,r/4,sub3144,author1757,2022-11-03 15:42:20,0.95,subreddit4,subreddit4_subs_anon
2,r/4,sub3145,author1758,2022-10-31 13:39:29,1.0,subreddit4,subreddit4_subs_anon
3,r/4,sub3146,author1759,2022-10-14 21:13:00,0.5,subreddit4,subreddit4_subs_anon
4,r/4,sub3147,author1760,2022-10-10 15:07:49,0.5,subreddit4,subreddit4_subs_anon
5,r/4,sub3148,author1761,2022-10-05 22:03:29,1.0,subreddit4,subreddit4_subs_anon
6,r/4,sub3149,author1762,2022-10-05 20:57:39,0.75,subreddit4,subreddit4_subs_anon
7,r/4,sub3150,author1763,2022-09-30 03:33:05,0.75,subreddit4,subreddit4_subs_anon
8,r/4,sub3151,author208,2022-09-29 18:45:28,0.9,subreddit4,subreddit4_subs_anon
9,r/4,sub3152,author1758,2022-09-25 14:01:24,0.1,subreddit4,subreddit4_subs_anon

In [17]:
threads["predicted_stance_scores"] = pd.to_numeric(
    threads["predicted_stance_scores"], errors="coerce"
)

In [20]:
print(threads["predicted_stance_scores"].dtype)          # float64
print(threads["predicted_stance_scores"].isna().sum())   # number of NI + original NaN
threads.to_parquet("data/threads.parquet")

float64
115223

In [22]:
submissions.to_parquet("data/submissions.parquet")